### ISSUE TITLE
mistyped particle causes server crash

### ISSUE THREAD

**Issue by netcore10** [mt1006/ParticleGenerator#1]
this needs a failsafe, because it can takedown servers

**Comment by mt1006** [comment]
I checked it and I was unable to crash the server. What did you exactly do and on which version?

**Comment by netcore10** [comment]
latest version, gave the smoke example changed the particle id to a modded one but it was mistyped, the moment you place it, the server crashes with a particle is null exception.

**Comment by netcore10** [comment]
but it forces the server to restart (This happens if you mistype any particle, but it does work when it's typed properly)

**Comment by mt1006** [comment]
For me it works fine. The mod also checks if the value of particle is null, so I think it shouldn't crash.
Could you send me logs?
![2022-05-23_16 07 00](https://user-images.githubusercontent.com/34820479/169838133-8161d71e-2eb7-40be-a237-8fccb838e4b2.png)

**Comment by netcore10** [comment]
Here they are: 
[logs_latest.log](https://github.com/mt1006/ParticleGenerator/files/8755954/logs_latest.log)
[crash-reports_crash-2022-05-23_10.25.57-server.txt](https://github.com/mt1006/ParticleGenerator/files/8755959/crash-reports_crash-2022-05-23_10.25.57-server.txt)

**Comment by mt1006** [comment]
Ok, I'll fix it soon.

**Comment by mt1006** [comment]
btw thanks for reporting
